[2024-04-17 20:38:48,400] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.18:5000 - call_trace=C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-17 20:38:48,403] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-17 20:38:48,407] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-17 20:39:15,920] INFO _log() L96   127.0.0.1 - - [17/Apr/2024 20:39:15] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-17 20:39:16,076] INFO _log() L96   127.0.0.1 - - [17/Apr/2024 20:39:16] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-17 20:39:16,098] INFO _log() L96   127.0.0.1 - - [17/Apr/2024 20:39:16] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-17 20:39:16,108] INFO _log() L96   127.0.0.1 - - [17/Apr/2024 20:39:16] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-17 20:39:16,256] INFO _log() L96   127.0.0.1 - - [17/Apr/2024 20:39:16] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-17 20:39:16,331] INFO _log() L96   127.0.0.1 - - [17/Apr/2024 20:39:16] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-17 20:39:35,665] ERROR log_exception() L838  Exception on /comentario [PUT] - call_trace=C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\flask\app.py L838 
Traceback (most recent call last):
  File "C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\app.py", line 227, in atualiza_reserva
    reserva = Reserva(
              ^^^^^^^^
TypeError: __init__() got an unexpected keyword argument 'id'
[2024-04-17 20:39:35,670] INFO _log() L96   127.0.0.1 - - [17/Apr/2024 20:39:35] "[35m[1mPUT /comentario HTTP/1.1[0m" 500 - - call_trace=C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-17 20:41:50,108] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.18:5000 - call_trace=C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-17 20:41:50,109] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-17 20:41:50,112] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-17 20:41:54,826] INFO _log() L96   127.0.0.1 - - [17/Apr/2024 20:41:54] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-17 20:41:54,989] INFO _log() L96   127.0.0.1 - - [17/Apr/2024 20:41:54] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-17 20:41:55,015] INFO _log() L96   127.0.0.1 - - [17/Apr/2024 20:41:55] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-17 20:41:55,023] INFO _log() L96   127.0.0.1 - - [17/Apr/2024 20:41:55] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-17 20:41:55,083] INFO _log() L96   127.0.0.1 - - [17/Apr/2024 20:41:55] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-17 20:41:55,153] INFO _log() L96   127.0.0.1 - - [17/Apr/2024 20:41:55] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-17 20:42:17,247] ERROR log_exception() L838  Exception on /reserva [POST] - call_trace=C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\flask\app.py L838 
Traceback (most recent call last):
  File "C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\app.py", line 167, in cria_reserva
    reserva = Reserva(
              ^^^^^^^^
TypeError: __init__() missing 1 required positional argument: 'id'
[2024-04-17 20:42:17,252] INFO _log() L96   127.0.0.1 - - [17/Apr/2024 20:42:17] "[35m[1mPOST /reserva HTTP/1.1[0m" 500 - - call_trace=C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-17 20:42:29,122] INFO _log() L96   127.0.0.1 - - [17/Apr/2024 20:42:29] "[35m[1mPOST /reserva HTTP/1.1[0m" 500 - - call_trace=C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-17 20:43:11,795] INFO _log() L96    * Detected change in 'C:\\Users\\ff_rj\\Documents\\Backend VAAlugar\\VAAlugar-back\\model\\reservas.py', reloading - call_trace=C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-17 20:43:11,937] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-17 20:43:16,452] INFO _log() L96   127.0.0.1 - - [17/Apr/2024 20:43:16] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\ff_rj\Documents\Backend VAAlugar\VAAlugar-back\env\Lib\site-packages\werkzeug\_internal.py L96  
